# Generated by Django 2.2 on 2021-11-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='items',
        ),
    ]
